{
 "title": "Point Detector",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg(rate(http_server_requests_seconds_bucket[1m])) BY (le))",
     "legendFormat": "0.5p"
    },
    {
     "expr": "histogram_quantile(0.75, avg(rate(http_server_requests_seconds_bucket[1m])) BY (le))",
     "legendFormat": "0.75p"
    },
    {
     "expr": "histogram_quantile(0.9, avg(rate(http_server_requests_seconds_bucket[1m])) BY (le))",
     "legendFormat": "0.9p"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(http_server_requests_seconds_bucket[1m])) BY (le))",
     "legendFormat": "0.95p"
    },
    {
     "expr": "histogram_quantile(0.99, avg(rate(http_server_requests_seconds_bucket[1m])) BY (le))",
     "legendFormat": "0.99p"
    }
   ]
  },
  { "title": "RPS and errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RPS by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[10s])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "RPS + status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate((http_server_requests_seconds_count[10s])) )by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}